#!/usr/bin/env python
#
# z80emu.py
#
# Originally generated by ChatGPT to create a compatibility layer between the
# old library and the new cffi based interface.
#

import logging
from _z80emu_cffi import ffi as _ffi
from _z80emu_cffi import lib as _lib
# Import these to export the constants as part of the z80emu API
from _z80emu_cffi.lib import TRACK_NONE, TRACK_RD, TRACK_WR, TRACK_EXEC, Z80_MEM_SIZE

_in_callback = None
_out_callback = None
_pending_callback_exception = None

log_io = logging.getLogger("mycron.trace.io")

def _callback_error(exc_type, exc_value, exc_tb):
    global _pending_callback_exception

    if _pending_callback_exception is None:
        _pending_callback_exception = (exc_value, exc_tb)


def _raise_pending_callback_exception():
    global _pending_callback_exception

    pending = _pending_callback_exception
    _pending_callback_exception = None

    if pending is not None:
        exc, tb = pending
        raise exc.with_traceback(tb)


@_ffi.callback(
    "unsigned char(unsigned char)",
    error=0,
    onerror=_callback_error)
def _c_io_in(port):
    global _in_callback
    port = int(port) & 0xff

    if _pending_callback_exception is not None:
        return 0

    if _in_callback is None:
        log_io.info(f"Z80_In {port:02x}")
        return 0

    return int(_in_callback(port)) & 0xff


@_ffi.callback("void(unsigned char, unsigned char)",
              onerror=_callback_error)
def _c_io_out(port, value):
    global _out_callback
    port = int(port) & 0xff
    value = int(value) & 0xff

    if _pending_callback_exception is not None:
        return

    if _out_callback is None:
        log_io.info(f"Z80_Out {port:02x} <- {value:02x}")
        return

    _out_callback(port, value)


_lib.z80emu_set_io_callbacks(_c_io_in, _c_io_out)


def reset():
    global _pending_callback_exception

    _pending_callback_exception = None
    _lib.z80emu_reset()


def set_in_callback(cb):
    global _in_callback

    if cb is not None and not callable(cb):
        raise TypeError("parameter must be callable or None")

    _in_callback = cb


def set_out_callback(cb):
    global _out_callback

    if cb is not None and not callable(cb):
        raise TypeError("parameter must be callable or None")

    _out_callback = cb


def mem_rd(addr):
    return int(_lib.z80emu_mem_rd(int(addr) & 0xffff))


def mem_wr(addr, val):
    """
    Debugger/backdoor memory write.

    This bypasses memory protection, matching your old CPython extension.
    Emulated CPU writes still go through C-side protection.
    """

    _lib.z80emu_mem_wr(int(addr) & 0xffff, int(val) & 0xff)


def _validate_memory_range(start, end):
    start = int(start)
    end = int(end)

    if not 0 <= start <= end <= Z80_MEM_SIZE:
        raise ValueError(
            f"invalid memory range [{start}, {end})"
        )

    return start, end


def mem_set_prot(start, end, val):
    """
    Set memory protection over [start, end).

    0 = writable
    nonzero = protected
    """
    start, end = _validate_memory_range(start, end)
    _lib.z80emu_mem_set_prot(start, end, int(val) & 0xff)


def mem_set_track_mask(start, end, mask):
    start, end = _validate_memory_range(start, end)

    _lib.z80emu_mem_set_track_mask(start, end, int(mask) & 0xff)


def mem_unset_track_mask(start, end, mask):
    start, end = _validate_memory_range(start, end)

    _lib.z80emu_mem_unset_track_mask(start, end, int(mask) & 0xff)


def mem_dis(pc):
    buf = _ffi.new("char[120]")
    n = _lib.z80emu_mem_dis(int(pc) & 0xffff, buf, len(buf))
    s = _ffi.string(buf).decode("ascii", errors="replace")
    return int(n), s


def get_regs():
    r = _ffi.new("z80emu_regs_t *")
    _lib.z80emu_get_regs(r)

    return {
        "PC": int(r.PC),
        "SP": int(r.SP),
        "AF": int(r.AF),
        "BC": int(r.BC),
        "DE": int(r.DE),
        "HL": int(r.HL),
        "IX": int(r.IX),
        "IY": int(r.IY),

        "AF2": int(r.AF2),
        "BC2": int(r.BC2),
        "DE2": int(r.DE2),
        "HL2": int(r.HL2),

        "IFF1": int(r.IFF1),
        "IFF2": int(r.IFF2),
        "IM": int(r.IM),
        "I": int(r.I),
        "R": int(r.R),
        "R2": int(r.R2),
    }


def raw_memory():
    """
    Returns a writable buffer view of the full 64 KiB memory.

    Warning: this bypasses PROM/write protection.
    Useful for debugging.
    """

    return _ffi.buffer(_lib.z80emu_memory(), Z80_MEM_SIZE)


def memory_snapshot():
    """Returns a snapshot/copy of the full 64 KiB memory."""
    return bytes(raw_memory())


# TODO: consider removing. It might be useful for functionality
# that injects a program directly into memory while protecting the proms.
def raw_memory_prot():
    return _ffi.buffer(_lib.z80emu_memory_prot(), Z80_MEM_SIZE)


def set_irq_line(active=True, vector=0xff):
    """
    Level-style IRQ.

    If active is true, the C backend calls z80ex_int() before each step.
    If active is false, the IRQ line is deasserted.
    """

    _lib.z80emu_set_irq_line(1 if active else 0, int(vector) & 0xff)


def clear_irq_line():
    _lib.z80emu_set_irq_line(0, 0xff)


def pulse_irq(vector=0xff):
    """
    Pulse/attempt one interrupt acknowledge.
    Returns z80ex's reported interrupt cycle count/result.
    """

    return int(_lib.z80emu_pulse_irq(int(vector) & 0xff))


def nmi():
    return int(_lib.z80emu_nmi())


def run_steps(n_steps=1000, chunk_size=10_000):
    """Runs N steps/instructions where N > 0.
    Also checks for pending exceptions from callbacks.
    If n_steps is large, it will split the execution into chunks
    of 'chunk_size' to avoid blocking exception handling for too long.
    """
    remaining = int(n_steps)
    chunk_size = int(chunk_size)

    if remaining < 0:
        raise ValueError("n_steps must be non-negative")
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")

    while remaining:
        chunk = min(remaining, chunk_size)
        _lib.z80emu_run_steps(chunk)
        _raise_pending_callback_exception()
        remaining -= chunk
